### ISSUE TITLE
Which are the 19 maps from the paper

### ISSUE THREAD

**Issue by cchaswell** [netneurolab/hansen_receptors#3]
Not really an issue but a question. I am unclear which nifti files are the 19 from Figure 1 from the paper titled "Mapping neurotransmitter systems to the structural and functional organization of the human neocortex." Can you point me in the direction of those 19 maps?

**Comment by justinehansen** [comment]
Hey @cchaswell, thanks for reaching out 🙂 

Some of the receptor maps come from combining multiple nifti images, which is why there aren't 19 nifti files corresponding to the 19 receptors/transporters. All volumetric receptor maps are available at [data/PET_nifti_images/](https://github.com/netneurolab/hansen_receptors/tree/main/data/PET_nifti_images), but this includes files that I don't use in the final set of 19 (they are used in supplementary analyses). [This script](https://github.com/netneurolab/hansen_receptors/blob/main/code/make_receptor_matrix.py#L22) shows a list of the files that I use for the final set of 19 receptors, and in that same script, I take weighted averages for some of the maps (eg D2, VAChT). Note that the files are .csv because they were parcellated using [this script](https://github.com/netneurolab/hansen_receptors/blob/main/code/parcellate.py).

That said, if you're just looking for a set of 19 nifti images, feel free to bypass the weighted averaging step. The images all look quite similar to one another (post normalization), as shown in Supplementary Figure 13 (pg 30 of [Supplementary Information](https://www.nature.com/articles/s41593-022-01186-3#Sec26)). You can pick a single representative tracer image for each receptor, based on number of controls (indicated in the file name - "hc36" stands for "36 healthy controls"), or sex ratios, or age etc (full info on all tracers available in [Table S3](https://github.com/netneurolab/hansen_receptors/tree/main/manuscript)).

Let me know if there's anything else I can help with or clarify.

Best,
Justine
